version: '3'
services:
  db:
    container_name: unbhelp-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: unbhelp
    ports:
      - 5432:5432
    networks:
      - unbhelp-network
#    volumes:
#      - ./data:/var/lib/postgresql/data
  backend:
    container_name: unbhelp-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - unbhelp-network

networks:
  unbhelp-network: