version: '3'
services:
  db:
    container_name: postgres-unbhelp
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: unbhelp
    ports:
      - 5432:5432
#    volumes:
#      - ./data:/var/lib/postgresql/data
