version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: unbhelp
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
